### ISSUE TITLE
request: namespace-agnostic helm chart

### ISSUE THREAD

**Issue by henriklb** [mowoe/hyperglass-helm#1]
I'd like to request an namespace-agnostic helm chart.

I tried to implement this helm chart on an Red Hat Openshift sandbox. I don't believe I have the option to set/create a custom namespaces there. The current chart fails as it expect certain configmaps etc. to be in the `hyperglass` namespace

**Comment by mowoe** [comment]
Hi @henriklb,

thank you for reaching out! 
To be quite honest, i didnt think about deployments on OpenShift. I have applied some changes, which are now released with version `v0.2.1` which should address this issue. Feel free to take a look at the updated instructions in the README to see if the deployment works now for you. 

Feel free to reach out and/or reopen this issue if thats not the case!

**Comment by henriklb** [comment]
thank you for the lightning quick solution ! Much appreciated. 

I will test this tomorrow. Will let you know should I encounter any problem. Thanks again
