### ISSUE TITLE
config-files volumes inaccessible as non-root user

### ISSUE THREAD

**Issue by henriklb** [mowoe/hyperglass-helm#4]
When attempting to run this image on redhat openshift it fails as it can't access the configuration files at `/root/hyperglass/devices.yaml` and `/root/hyperglass/hyperglass.yaml`. https://github.com/mowoe/hyperglass-helm/blob/6f651c2787529aeeebb37fadb0ab34fb6ca87932/charts/hyperglass/templates/deployment.yaml#L43

```
RuntimeError:
No configuration directories were determined to both exist and be readable
by hyperglass. hyperglass is running as user '1003550000' (UID '1003550000'), and tried
to access the following directories:
- /hyperglass
- /etc/hyperglass
```
I believe this is due to openshift not allowing containers to be ran as root. 

Do you know if there are other files/processes that also require root-level access in order to run?  

Let me know if you need any more info. I'd be happy to help/test. 

(You could also test via the free openshift sandbox:
1. register for openshift sandbox access:
https://developers.redhat.com/developer-sandbox
2. connect to openshift cluster with `oc connect` followed by familiar `kubectl` commands:
https://developers.redhat.com/blog/2021/04/21/access-your-developer-sandbox-for-red-hat-openshift-from-the-command-line# )

**Comment by henriklb** [comment]
openshift is running the container with the following uid and gid. The uid is dynamic/arbitrary. While the gid is the same every time.
```
$ id
uid=1003550000(1003550000) gid=0(root) groups=0(root),1003550000
```

I found some info here: https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines 

>Support Arbitrary User IDs
By default, OpenShift Container Platform runs containers using an arbitrarily assigned user ID. This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node.
For an image to support running as an arbitrary user, directories and files that may be written to by processes in the image should be owned by the root group and be read/writable by that group. Files to be executed should also have group execute permissions.
Adding the following to your Dockerfile sets the directory and file permissions to allow users in the root group to access them in the built image:
```
RUN chgrp -R 0 /some/directory && \
    chmod -R g+rwX /some/directory
```
>Because the container user is always a member of the root group, the container user can read and write these files.

>In addition, the processes running in the container must not listen on privileged ports (ports below 1024), since they are not running as a privileged user.

**Comment by mowoe** [comment]
I think it should be possible to set the `fsGroup` in `securityContext` for the deployment in order to ensure that the mounted configmaps are owned by gid `0`. I will check if this works.

Thanks for the hints to the sandbox openshift instance!

**Comment by henriklb** [comment]
Thank you!

In case you missed it:
>In addition, the processes running in the container must not listen on privileged ports (ports below 1024), since they are not running as a privileged user.

The hyperglass application would probably need to change its `listen_port: 80` in  `hyperglass.yaml` to something above 1024. And the port change would possibly need to be reflected in the `deployment.yaml` too, if I understand correctly. https://github.com/mowoe/hyperglass-helm/blob/6f651c2787529aeeebb37fadb0ab34fb6ca87932/charts/hyperglass/templates/deployment.yaml#L22

**Comment by mowoe** [comment]
I have made some progress in #5  but due to hyperglass being this bloaty monolithic application, its a bit tedious. In theory, i got it to work now. But i cant really test this, because during the hyperglass startup, it wants to have more memory than the openshift devbox can supply. 
If you have a "real" openshift instance, feel free to test the feature branch (just checkout the branch locally and run `helm install` in `charts/hyperglass`) and check if it is any better now.

**Comment by mowoe** [comment]
I think this should be fixed by #5 . I tried it in the openshift sandbox and it works for me. Maybe you could also test the feature branch:
```bash
git clone git@github.com:mowoe/hyperglass-helm.git
git checkout feature/fix-openshift
cd charts/hyperglass
helm install \
    --set primary_asn=123456 \
    --set site_title="My cool Lookingglass" \
    --set-file devices_config=devices.yaml \
    my-cool-lookingglass . 
```

**Comment by henriklb** [comment]
Thank you very much for your work.

just quick and dirty testing with the feature/fix-openshift branch (in the sandbox) it appears  the hyperglass process is running, but it is not listening to any port.

```
1003550000@hyperglass-deployment-699dcb6666-pwqj5:/$ ss -ln4
Netid       State        Recv-Q       Send-Q             Local Address:Port             Peer Address:Port       
tcp         LISTEN       0            0                        0.0.0.0:6379                  0.0.0.0:*  
```


I will be able to test more later today.

I get the following "warning" event:
```
[hyperglass-deployment-699dcb6666-pwqj5]](https://console-openshift-console.apps.sandbox-m3.1530.p1.openshiftapps.com/k8s/cluster/namespaces/henriklb-dev)
Sep 8, 2023, 8:46 AM
Generated from kubelet on ip-10-0-148-113.ec2.internal
109 times in the last 23 minutes
Startup probe failed: Get "http://10.128.43.30:8080/": dial tcp 10.128.43.30:8080: connect: connection refused
```
Could this be due to the liveness probe is still checking port 80 in the deployment?




The bottom of the log output 

```
...
x_order_2: colinear!
x_order_2: colinear!
[INFO] 20230908 06:45:22 | hyperglass.util.frontend:362 | build_frontend → Starting UI build...
[SUCCESS] 20230908 06:48:37 | hyperglass.util.frontend:386 | build_frontend → Completed UI build
❌ Stopping hyperglass due to keyboard interrupt.
Error: [Errno 1] Operation not permitted
[ERROR] 20230908 06:48:37 | hyperglass.util.frontend:401 | build_frontend → [Errno 1] Operation not permitted
```

**Comment by mowoe** [comment]
Sorry for the confusion. Yesterday i had used a different image tag, but i have now pushed the changes to the `:latest` tag. So it should work now. You may need to redeploy with helm to ensure the new image gets pulled. 
Just for reference, this is my output:
```
_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
[INFO] 20230907 23:19:52 | hyperglass.util.frontend:363 | build_frontend → Starting UI build...
[SUCCESS] 20230907 23:22:37 | hyperglass.util.frontend:387 | build_frontend → Completed UI build
[SUCCESS] 20230907 23:22:38 | hyperglass.main:138 | on_starting → Started hyperglass 1.0.4 on http://[::]:8080 with 1 workers
```

Im currently trying to debug a different issue, i set the listening address to a v6, but in openshift, this doesnt seem to translate to the process listening on v4 and v6 like it does in kubernetes. This causes the readiness probe to fail, maybe i need to switch back to a v4 listening address.

**Comment by mowoe** [comment]
Should be fixed now too, feel free to try again , sorry for the ping-pong ;)

**Comment by henriklb** [comment]
Awesome! It appears to be running fine now. I haven't verified with an ingress yet, but I assume it is all good :)

**Comment by henriklb** [comment]
This might not be on-topic and maybe too openshift-specific: 
 
 I've made multiple attempt to expose the hyperglass service via a openshift's `route` command but without luck (the openshfit dev sandbox does not support ingress, while regular openshift does). 
 
Have you been able to do expose the hyperglass service in openshift via "route"?

**Comment by mowoe** [comment]
Unfourtunately i dont have access to a 'real' openshift instance so i cant really debug this well. Im also not sure i 100% understand the 'route' object in openshift. 

Still, i have some thoughts:

First, i would try to remove this line:
https://github.com/mowoe/hyperglass-helm/blob/feature/fix-openshift/charts/hyperglass/templates/deployment.yaml#L83

In the httpd examples from openshift, i saw that theres no service type configured and im not sure which one is the default. So i would just remove it for testing.


But other than that, i would also just try to modify [this](https://github.com/openshift-helm-charts/charts/blob/main/charts/redhat/redhat/httpd-template/0.0.4/src/templates/route.yaml) example a bit and see if that works. 
I will do some further debugging and let you know if i find something.

**Comment by henriklb** [comment]
I managed to get a route working just now. I changed both the `port` and  `targetPort` to 8080 in the service.  https://github.com/mowoe/hyperglass-helm/blob/1990207208f11b16d05f4fce52c9673a0e2acd51/charts/hyperglass/templates/deployment.yaml#L77C13-L77C15

**Comment by henriklb** [comment]
This is my exact hyperglass-service.yaml file that is working with the openshift route. I dont think the ipFamilyPolicy matter:
```
apiVersion: v1
kind: Service
metadata:
  name: hyperglass-service
spec:
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hyperglass
  sessionAffinity: None
  type: {{ .Values.service_type }}
```

**Comment by mowoe** [comment]
In theory the `targetPort` shouldnt be necessary. Before it was mapped to the container port which is also 8080. 
If you dont specify a `targetPort` at all, it will be set to `port`, so also 8080 in this case.

**Comment by henriklb** [comment]
Then `port` is likely the only culprit. I just changed both at the same time, maybe not the smartest when trying to find the root cause.

**Comment by mowoe** [comment]
I changed the port in #5 , i will do some more testing and then i can hopefully merge it.

**Comment by mowoe** [comment]
I will close this as it is fixed i would say.
