### ISSUE TITLE
How can I update config values?

### ISSUE THREAD

**Issue by romagn** [mowoe/hyperglass-helm#6]
Hi, I have deployed hyperglass via your helm chart with flux, but I needed to update some of it's config values. I needed to change some of the global values and I wanted to enable the rest api on it.
With your chart it seems the configuration is hard set by https://github.com/mowoe/hyperglass-helm/blob/main/charts/hyperglass/templates/configmap.yaml

**Comment by mowoe** [comment]
Hi @romagn,

youre right, some of the values are currenlty hardcoded, if you tell me which ones you need, i can add them as configurable.

**Comment by romagn** [comment]
I was looking at flux documentation to see if I could patch the current configmap but it seems it's not trivial. Anyway what I needed was to enable the API [documentation](https://hyperglass.dev/docs/rest-api/) and set both the request_timeout and netmiko_delay_factor in the global settings [documentation](https://hyperglass.dev/docs/parameters).
Thanks for the quick reply

**Comment by mowoe** [comment]
Im using argocd so i dont know a whole lot about flux, but i suppose it works the same. You wont be able to easily patch the configmap using those tools as they will resync it with tht source of truth and overwrite your changes. Anyway, i will create the necessary changes which will allow you to set the options.

Anyways, the API should be enabled by default i think. The first link you provided only talks about the api documentation (so swaggerUI and so on)

**Comment by henriklb** [comment]
If feasible, another approach could be to create configmaps of all of the .yaml-files hyperglass requires (hyperglass.yaml,  commands.yaml etc.). Similar to what you have done with devices.yaml. That way, a user migrating from a bare-metal/vm-deployment of hyperglass could simply copy their yaml-files over to this helm chart. 


I don't have the detailed knowledge on how this chart is implementet tho, so take this with a grain of salt. 

EDIT: This is just me trying to think ahead before another request/issue pops up asking to expose another part of the config :)

**Comment by mowoe** [comment]
I would propose a slightly different approach: Having the possibility to use all three config files as Configmaps, so migrating from existing deployments would be easy, but also having the possibility to use the chart values instead of that.

**Comment by romagn** [comment]
I also think that's the best approach. Thanks

**Comment by mowoe** [comment]
Helm chart verstion `v1` has been released. This allows you to supply your own config files. See the README for more information. Feel free to reopen this issue if you face additional challenges.

**Comment by romagn** [comment]
Thanks

**Comment by henriklb** [comment]
Thanks! Well done
